@echo off
echo 正在启动 Edge 浏览器（远程调试模式）...
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --remote-debugging-port=9222 --user-data-dir="C:\temp\edge-profile"
echo 浏览器已启动，请保持此窗口打开...
pause